# Generated by Django 5.0.7 on 2024-07-26 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Yarn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=255)),
                ('makeup', models.CharField(max_length=255)),
                ('price', models.FloatField(verbose_name='cost(R) per skein')),
                ('weight', models.FloatField(verbose_name='weight(g) per skein')),
                ('in_stock', models.IntegerField(verbose_name='quantity stocked')),
                ('img_url', models.CharField(max_length=255, verbose_name='image location')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('yarn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storefront.yarn')),
            ],
        ),
    ]
