# Generated by Django 5.0.7 on 2024-07-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0002_review_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yarn',
            name='price',
            field=models.IntegerField(verbose_name='cost(R) per skein'),
        ),
        migrations.AlterField(
            model_name='yarn',
            name='weight',
            field=models.IntegerField(verbose_name='weight(g) per skein'),
        ),
    ]
